"""add ticket_id and ticket_ref to contacts quotes jobs

Revision ID: 12860312c804
Revises: 0d91efc0794c
Create Date: 2026-05-07 14:28:38.571805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12860312c804'
down_revision = '0d91efc0794c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('ticket_ref', sa.String(length=20), nullable=True))

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('ticket_ref', sa.String(length=20), nullable=True))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('ticket_ref', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('ticket_ref')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('ticket_ref')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('ticket_ref')
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###
